#!/usr/bin/env bash

bucket_name="$1"


if [ -z "$bucket_name" ]; then
  echo "These are the buckets available in your AWS account:"
  aws s3 ls | awk '{print $3}'
  read -p "Please provide a valid bucket name to delete here: " bucket_name
fi

if [ -z "$bucket_name" ]; then
  echo "Bucket name is required."
  exit 1
fi

read -p "Does the bucket '$bucket_name' contain versioning data? [Y/n]: " versioning_check

if [[ "$versioning_check" == "Y" || "$versioning_check" == "y" || -z "$versioning_check" ]]; then
  echo "Deleting all objects in the versioning bucket '$bucket_name'..."
  aws s3api delete-objects --bucket $bucket_name \
  --delete "$(aws s3api list-object-versions \
      --bucket "$bucket_name" \
      --output=json \
      --query='{Objects: Versions[].{Key:Key,VersionId:VersionId}}')"

elif [[ "$versioning_check" == "N" || "$versioning_check" == "n" ]]; then
  echo "Deleting all objects in the bucket '$bucket_name'..."
  aws s3 rm s3://$bucket_name --recursive

else
  echo "Invalid input. Please enter 'Y' or 'N'."
  exit 1
fi

echo "Deleting the bucket '$bucket_name'..."
aws s3api delete-bucket --bucket "$bucket_name"

echo "You curently have the following buckets in your AWS account:"
aws s3 ls | awk '{print $3}'

